# Generated by Django 4.0.3 on 2022-04-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourM', '0003_provinces'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Provinces',
            field=models.CharField(default='', max_length=255),
        ),
    ]
