# Generated by Django 4.0.3 on 2022-04-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourM', '0004_post_provinces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creator',
            field=models.CharField(default='The company', max_length=255),
        ),
    ]
