# Generated by Django 4.0.3 on 2022-04-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourM', '0006_post_pack_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.CharField(default='', max_length=255),
        ),
    ]
