# Generated by Django 4.0.3 on 2022-04-18 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourM', '0009_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='members',
        ),
    ]
