# Generated by Django 4.0.3 on 2022-04-18 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourM', '0010_rename_users_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='members',
            new_name='comments',
        ),
    ]
