# Generated by Django 4.0.3 on 2022-04-27 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourM', '0011_rename_members_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comments',
        ),
        migrations.AlterField(
            model_name='post',
            name='days',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=''),
        ),
    ]
