# Generated by Django 4.0.3 on 2022-04-27 01:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourM', '0012_delete_comments_alter_post_days_alter_post_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='days',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
