# Generated by Django 4.0.3 on 2022-05-01 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourM', '0021_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Size',
            field=models.PositiveIntegerField(default='1', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
