# Generated by Django 4.0.3 on 2022-05-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourM', '0022_post_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Hoster',
            field=models.TextField(default=''),
        ),
    ]
