# Generated by Django 4.0.3 on 2022-05-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourM', '0023_post_hoster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Hoster',
            field=models.CharField(max_length=255),
        ),
    ]
