# Generated by Django 4.0.3 on 2022-05-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourM', '0024_alter_post_hoster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provinces',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Provinces',
        ),
    ]
