# Generated by Django 4.0.3 on 2022-05-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourM', '0026_post_provinces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Provinces',
        ),
    ]
