# Generated by Django 4.0.3 on 2022-05-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourM', '0027_remove_post_provinces'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Provinces', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='Provinces',
            field=models.CharField(default='', max_length=255),
        ),
    ]
