# Generated by Django 4.0.3 on 2022-05-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourM', '0028_provinces_post_provinces'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Accomodation',
            field=models.TextField(default='-', max_length=255),
        ),
    ]
