# Generated by Django 4.0.3 on 2022-05-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourM', '0029_post_accomodation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Accomodation',
            field=models.URLField(),
        ),
    ]
