# Generated by Django 3.2.8 on 2022-05-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourM', '0031_remove_post_creator_alter_post_accomodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pack_img2',
            field=models.ImageField(blank=True, null=True, upload_to='pacImages/'),
        ),
    ]
