# Generated by Django 3.2.8 on 2022-05-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourM', '0032_post_pack_img2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pack_img1',
            field=models.ImageField(blank=True, null=True, upload_to='pacImages/'),
        ),
        migrations.AddField(
            model_name='post',
            name='pack_img3',
            field=models.ImageField(blank=True, null=True, upload_to='pacImages/'),
        ),
        migrations.AddField(
            model_name='post',
            name='pack_img4',
            field=models.ImageField(blank=True, null=True, upload_to='pacImages/'),
        ),
    ]
