# Generated by Django 3.2.8 on 2022-05-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourM', '0034_enrol'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='enrol',
            new_name='enroll',
        ),
    ]
