# Generated by Django 3.2.8 on 2022-05-08 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourM', '0036_remove_enroll_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='username',
            new_name='name',
        ),
    ]
