# Generated by Django 3.2.8 on 2022-05-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourM', '0037_rename_username_enroll_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='name',
            new_name='username',
        ),
    ]
