# Generated by Django 3.2.8 on 2022-05-08 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TourM', '0038_rename_name_enroll_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='enrolls', to='TourM.post'),
        ),
    ]
