# Generated by Django 3.2.8 on 2022-05-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourM', '0039_enroll_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Transportation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='Provinces',
            field=models.CharField(default='in_desc', max_length=255),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='Provinces',
            field=models.CharField(default='in desc', max_length=255),
        ),
    ]
